### ISSUE TITLE
子ぽわみの Prefab を作成する

### ISSUE THREAD

**Issue by penpenpng** [penpenpng/Udon#7]
以下の要件を満たす Prefab を `Prefabs` フォルダの中に作成してください:

- 見た目は赤丸とする
- `Rigidbody2D` を持ち、重力の影響を受ける
- ~以下の要件を満たす Script を持つ:~
  - ~見た目を青丸に変更し、絶対座標を固定化するメソッドを持つ~

**Comment by Genroh** [comment]
resolve #15

**Comment by penpenpng** [comment]
Closed by #15
